namespace :suggestions do
  desc "Remove suggestions whose suggested entry doesn't exist anymore"
  task :prune => :environment do
    Suggestion.find_each(:batch_size => 10_000) do |suggestion|
      if !suggestion.user || !suggestion.entry
        if suggestion.user && suggestion.entry_id.present?
          suggestion.propagate_destruction(:delayed => false)
        end
        suggestion.delete
        print('.')
      end
    end
  end

  desc "Refreshes suggestions for all users"
  task :refresh => :environment do
    Rails.logger.info "Refreshing suggestions for users..."
    User.query.each do |user|
      user.refresh_suggestions
      user.save :validate => false
    end
  end

  desc "Delete all generated suggestions for all users"
  task :delete_all => :environment do
    Suggestion.find_each(:batch_size => 10_000,
                         :origin_id => nil) do |s|
      print( s.destroy ? '.' : 'E' )
    end
  end

  desc "Delete all suggestions that were not generated by users"
  task :delete_all_but_suggested_by_users => :environment do
    Suggestion.find_each(:batch_size => 10_000,
                         :reason.ne => "UserSuggested") do |s|
      print( s.destroy ? '.' : 'E' )
    end
  end
end
